version: '3.8'
services:
    php-apache:
        container_name: M300_LB3_php-apache
        restart: on-failure:10
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'
                reservations:
                    cpus: '1'
                    memory: '1g'
        env_file:
            - ./mysql/.env
        image: cantonerobin/m300_lb3_apache:latest
        #build:
        #    context: ./php
        #    dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
        networks:
            - backend
    db:
        container_name: M300_LB3_db
        image: cantonerobin/m300_lb3_mysql:latest
        #build:
        #    context: ./mysql
        #    dockerfile: Dockerfile
        restart: on-failure:10
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'
                reservations:
                    cpus: '1'
                    memory: '1g'
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "9906:3306"
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: M300_LB3_phpmyadmin
        restart: on-failure:10
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'
                reservations:
                    cpus: '1'
                    memory: '1g'
        environment:
            PMA_HOST: db
        ports:
            - '8080:80'
        depends_on:
            - db
        networks:
            - frontend
            - backend
    nginx:
        image: nginx:latest
        container_name: M300_LB3_nginx
        restart: on-failure:10
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: '2g'
                reservations:
                    cpus: '1'
                    memory: '1g'
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - frontend
            - backend

networks:
  frontend:
    external: true
    name: frontend
  backend:
    external: true
    name: backend