version: '3.8'
services:
    php-apache:
        container_name: M300_LB3_php-apache
        restart: unless-stopped
        env_file:
            - ./mysql/.env
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: M300_LB3_db
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: M300_LB3_phpmyadmin
        restart: unless-stopped
        env_file:
            - ./mysql/.env
        environment:
            PMA_HOST: db
        ports:
            - '8080:80'
        depends_on:
            - db
